import Navbar from "@/components/Navbar";
import "./globals.css";
import localFont from "next/font/local";
import Footer from "@/components/Footer";
import Providers from "@/components/Providers";

const gintronic = localFont({
  src: [
    {
      path: "fonts/Gintronic-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "fonts/Gintronic-Bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "fonts/Gintronic-RegularItalic.otf",
      weight: "400",
      style: "italic",
    },
    {
      path: "fonts/Gintronic-BoldItalic.otf",
      weight: "700",
      style: "italic",
    },
  ],
  variable: "--font-gintronic",
});

export const metadata = {
  title: "geevee studio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${gintronic.variable}`}>
      <body className="list-none bg-slate-200 text-slate-800 transition-all duration-700 dark:bg-gray-800 dark:text-slate-200">
        <Providers>
          <Navbar />
          <div className="mx-auto max-w-7xl">{children}</div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
